#!/bin/sh

#set -e

#echo "IM HERE"

#mkdir ~/rstem
#mkdir ~/rstem/cellapps
#cp -r ./cellapps ~/rstem
#mkdir ~/rstem/projects
#cp -r ./projects ~/rstem


# TODO: detect running on raspberry pi then set up SPI, etc...
