#!/bin/bash


# Copy udev rule to correct place
sudo cp ./90-raspberrystem.rules /etc/udev/rules.d/90-raspberrystem.rules

# Set up SPI, I2C, etc...

# lines to be in /etc/modules:
declare -a modules=('i2c-bcm2708' 'i2c-dev' 'spidev' 'snd-bcm2835');
for mod in ${modules[@]}; do
    if grep -q $mod /etc/modules; then
        echo "$mod already in /etc/modules."
    else
        echo "$mod not found in /etc/modules, adding...."
        echo $mod | sudo tee -a /etc/modules >> /dev/null
    fi
done

# lines to be commented out in /etc/modprobe.d/raspi-blacklist.conf:
declare -a blacklist=('i2c-bcm2708' 'spi-bcm2708');
for mod in ${blacklist[@]}; do
    if grep -q "^blacklist $mod" /etc/modprobe.d/raspi-blacklist.conf; then
        echo "$mod is blacklisted, commenting out...."
        sudo sed -i -e "s/blacklist $mod/#blacklist $mod/g" /etc/modprobe.d/raspi-blacklist.conf
    else
        echo "$mod is not blacklisted."
    fi
done